### ISSUE TITLE
Authorization header support

### ISSUE THREAD

**Issue by Indomitable** [Indomitable/api-mocker#2]
Add ability to verify JWT Bearer tokens if they a valid. Suggestion:
```yaml
authorization:
   type: Bearer
   issuer:  X
   audience: N
   publicKey: PK
   secretKey: SK
```
If request with not valid token comes return error.
